[package]
name = "argon_m2_fan_i2c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "~1.0.66"
i2cdev = "~0.5.1"
sysinfo = "~0.27.0"
lazy_static = "~1.4.0"